# -*- coding: euc-kr -*-

ESC =	""
CSI =	ESC + "["
BLK = ESC+"[0;30m"        # 색상 : Black    
RED = ESC+"[0;31m"        # 색상 : Red      
GRN = ESC+"[0;32m"        # 색상 : Green    
YEL = ESC+"[0;33m"        # 색상 : Yellow   
BLU = ESC+"[1;34m"        # 색상 : Blue     
MAG = ESC+"[0;35m"        # 색상 : Magenta  자주
CYN = ESC+"[0;36m"        # 색상 : Cyan     
WHT = ESC+"[0;37m"		 # 색상 : White    
HBL = ESC+"[1;30m"        # 색상 : 회색     
HIR = ESC+"[1;31m"        # 색상 : Red      
HIG = ESC+"[1;32m"        # 색상 : Green    
HIY = ESC+"[1;33m"        # 색상 : Yellow   
HIB = ESC+"[1;34m"        # 색상 : Blue     
HIM = ESC+"[1;35m"        # 색상 : Magenta  핑크
HIC = ESC+"[1;36m"        # 색상 : Cyan     하늘
HIW = ESC+"[1;37m"        # 색상 : White    
BBLK = ESC+"[40m"         # 색상 : Black    
BRED = ESC+"[41m"         # 색상 : Red      
BGRN = ESC+"[42m"         # 색상 : Green    
BYEL = ESC+"[43m"         # 색상 : Yellow   
BBLU = ESC+"[44m"         # 색상 : Blue     
BMAG = ESC+"[45m"         # 색상 : Magenta  
BCYN = ESC+"[46m"         # 색상 : Cyan     
BWHT = ESC+"[47m"         # 색상 : White    
HBRED = ESC+"[41;1m"      # 색상 : Red      
HBGRN = ESC+"[42;1m"      # 색상 : Green    
HBYEL = ESC+"[43;1m"      # 색상 : Yellow   
HBBLU = ESC+"[44;1m"      # 색상 : Blue     
HBMAG = ESC+"[45;1m"      # 색상 : Magenta  
HBCYN = ESC+"[46;1m"      # 색상 : Cyan     
HBWHT = ESC+"[47;1m"      # 색상 : White    
NOR = ESC+"[0;37;40m"     # 색상 : Puts everything back to normal 
BOLD = ESC+"[1m"          # 색상 : Turn on bold mode 
CLR = ESC+"[2J"           # 색상 : Clear the screen  
#REF = CLR+HOME           # 색상 : Clear screen and home cursor 
BIGTOP = ESC+"#3"         # 색상 : Dbl height characters, top half 
BIGBOT = ESC+"#4"         # 색상 : Dbl height characters, bottem half 
SAVEC = ESC+"[s"          # 색상 : Save cursor position 
REST = ESC+"[u"           # 색상 : Restore cursor to saved position 
REVINDEX = ESC+"M"        # 색상 : Scroll screen in opposite direction 
NORMALINDEX = ESC+"L"     # 색상 : Scroll screen in normal direction 
SINGW = ESC+"#5"          # 색상 : Normal, single-width characters 
DBL = ESC+"#6"            # 색상 : Creates double-width characters 
FRTOP = ESC+"[2;25r"      # 색상 : Freeze top line 
FRBOT = ESC+"[1;24r"      # 색상 : Freeze bottom line 
UNFR = ESC+"[r"           # 색상 : Unfreeze top and bottom lines 
BLINK = ESC+"[5m"         # 색상 : Initialize blink mode 
U = ESC+"[4m"             # 색상 : Initialize underscore mode 
REV = ESC+"[7m"           # 색상 : Turns reverse video mode on 
HIREV = ESC+"[1,7m"       # 색상 : Hi intensity reverse video  
HI = ESC+"[32m"

